name: compas-node
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs
  - bzip2
  - ca-certificates
  - compas
  - importlib_resources
  - intel-openmp
  - jsonschema
  - jsonschema-specifications
  - libblas
  - libcblas
  - libexpat
  - libffi
  - libhwloc
  - libiconv
  - liblapack
  - libsqlite
  - libxml2
  - libzlib
  - mkl
  - networkx
  - numpy
  - openssl
  - pip
  - pkgutil-resolve-name
  - python
  - python_abi
  - pyyaml
  - referencing
  - rpds-py
  - scipy
  - setuptools
  - tbb
  - tk
  - tzdata
  - wheel
  - xz
  - yaml
  - zipp
  - pip:
      - annotated-types
      - anyio
      - certifi
      - click
      - colorama
      - dnspython
      - email-validator
      - fastapi
      - fastapi-cli
      - h11
      - httpcore
      - httptools
      - httpx
      - idna
      - jinja2
      - markdown-it-py
      - markupsafe
      - mdurl
      - orjson
      - pydantic
      - pydantic-core
      - pygments
      - python-dotenv
      - python-multipart
      - rich
      - shellingham
      - sniffio
      - starlette
      - typer
      - typing-extensions
      - ujson
      - uvicorn
      - watchfiles
      - websockets
      - uvicorn
